CREATE TABLE [dbo].[CommunityImport]
(
	[Id] int PRIMARY KEY IDENTITY,
	[ProcessedOn] datetime NULL,
	[ImportId] UNIQUEIDENTIFIER NOT NULL,
	[CommunityId] int,
    [OrgId] int,
    [OrgName] varchar(100),
    [Description] varchar(500),
    [Raiting] int,
    [NumBeds] int,
    [CommunityName] varchar(100),
    [Facebook] varchar(50),
    [Twitter] varchar(50),
    [GooglePlus] varchar(50),
    [AnnualRevenue] int,
    [NumEmployees] int,
    [WebURL] varchar(100),
    [OfficePhone] varchar(50),
    [AltPhone] varchar(50),
    [TickerSymbol] varchar(10),
    [BillingLine1] varchar(100),
    [BillingLine2] varchar(100),
    [BillingCity] varchar(50),
    [BillingState] varchar(50),
    [BillingCountry] varchar(50),
    [BillingPostalCode] varchar(50),
    [ShippingLine1] varchar(100),
    [ShippingLine2] varchar(100),
    [ShippingCity] varchar(50),
    [ShippingState] varchar(50),
    [ShippingCountry] varchar(50),
    [ShippingPostalCode] varchar(50), 
    [CommunityType] VARCHAR(50) NULL, 
    [Industry] VARCHAR(50) NULL
)
