CREATE TABLE [dbo].[VendorImport]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,	
    [ImportId] uniqueidentifier,
	[VendorId] int,
	[OrgId] int,
	[VendorName] varchar(100),
    [OrgName] varchar(100),
    [BillingLine1] varchar(100),
    [BillingLine2] varchar(100),
    [BillingCity] varchar(50),
    [BillingState] varchar(50),
    [BillingCountry] varchar(50),
    [BillingPostalCode] varchar(50),
    [ShippingLine1] varchar(100),
    [ShippingLine2] varchar(100),
    [ShippingCity] varchar(50),
    [ShippingState] varchar(50),
    [ShippingCountry] varchar(50),
    [ShippingPostalCode] varchar(50),
    [Facebook] varchar(50),
    [Twitter] varchar(50),
    [GooglePlus] varchar(50),
    [AnnualRevenue] int,
    [NumEmployees] int,
    [WebURL] varchar(100),
    [OfficePhone] varchar(50),
    [AltPhone] varchar(50),
    [TickerSymbol] varchar(10),
	[ProcessedOn] datetime NULL,
    [Industry] VARCHAR(50) NULL
)
