//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllTheSame.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportErrorLog
    {
        public int Id { get; set; }
        public System.Guid ImportId { get; set; }
        public string Flat_File_Source_Error_Output_Column { get; set; }
        public Nullable<int> ErrorCode { get; set; }
        public string ErrorColumn { get; set; }
        public string ErrorDescription { get; set; }
    }
}
