//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllTheSame.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiosk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kiosk()
        {
            this.Alerts = new HashSet<Alert>();
            this.DataSyncs = new HashSet<DataSync>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CommunityId { get; set; }
        public int KioskStatusId { get; set; }
        public string Name { get; set; }
        public string Identifier { get; set; }
        public string IdentifierType { get; set; }
        public string OnSiteLocationDesc { get; set; }
        public int BadgesRemaining { get; set; }
        public int BadgeAlertCount { get; set; }
        public Nullable<System.DateTime> RestartTime { get; set; }
        public Nullable<int> SessionMaxHours { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alert> Alerts { get; set; }
        public virtual Community Community { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataSync> DataSyncs { get; set; }
        public virtual KioskStatus KioskStatu { get; set; }
    }
}
