//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllTheSame.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSession
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.Guid SessionId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Expiration { get; set; }
        public bool IsValid { get; set; }
        public byte[] Version { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
