//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllTheSame.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorCredDocument
    {
        public int Id { get; set; }
        public int VendorCredId { get; set; }
        public string Title { get; set; }
        public string URL { get; set; }
        public string Text { get; set; }
        public string DocType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual VendorCredential VendorCredential { get; set; }
    }
}
