//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllTheSame.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorCredential
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VendorCredential()
        {
            this.VendorCredDocuments = new HashSet<VendorCredDocument>();
        }
    
        public int Id { get; set; }
        public int RequirementId { get; set; }
        public int VendorWorkerId { get; set; }
        public bool IsAttested { get; set; }
        public bool IsConfirmed { get; set; }
        public Nullable<System.DateTime> ConfirmedOn { get; set; }
        public Nullable<int> ConfirmedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Requirement Requirement { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorCredDocument> VendorCredDocuments { get; set; }
        public virtual VendorWorker VendorWorker { get; set; }
    }
}
